>tr|a0a023dfe8|a0a023dfe8_9baci putative hydrolase os=geobacillus caldoxylosilyticus nbrc 107762 gn=gca01s_030_00190 pe=4 sv=1 gp

manvikarpklyvmdngrmrmdknwmiamhnpatihnpnaqtefvefpiytvlidhpegkilfdtscnpnsmgpqgrwaestqqmfpwtateecylhnrleqlkvrpediryvvashlhldhagclemftnatiivhedefngalqcyarnqkegayiwadidawiknnlqwrtvkrhednillaegvkvlnfgsghawgmlglhvelpetggiilasdaiytaesygppikppgiiydslgymntverirriaqetksqvwfghdaeqfkkfrkstegyye
>gi|211909965|ref|yp_002302326.1| green fluorescent protein (plasmid) [neisseria gonorrhoeae]
mskgeelftgvvpilveldgdvnghkfsvsgegegdatygkltlkficttgklpvpwptlvttfgygvqc
farypdhmkqhdffksampegyvqertiffkddgnyktraevkfegdtlvnrielkgidfkedgnilghk
leynynshnvyimadkqkngikvnfkirhniedgsvqladhyqqntpigdgpvllpdnhylstqsalskd
pnekrdhmvllefvtaagithgmdelyk

