>SABP2_Refrence
mkegkhfvlvhgachggwswyklkplleaaghkvtaldlaasgtdlrkieelrtlydytlplmelmeslsadekvilvghslggmnlglamekypqkiyaavflaafmpdsvhnssfvleqynertpaenwldtqflpygspeepltsmffgpkflahklyqlcspedlalasslvrpsslfmedlskakyftderfgsvkrvyivctedkgipeefqrwqidnigvteaieikgadhmamlcepqklcaslleiahkyn*

