>SABP2_Refrence
mkegkhfvlvhgachggwswyklkplleaaghkvtaldlaasgtdlrkieelrtlydytlplme

lmeslsadekvilvghslggmnlglamekypqkiyaavflaafmpdsvhnssfvleqynertpa

enwldtqflpygspeepltsmffgpkflahklyqlcspedlalasslvrpsslfmedlskakyf

tderfgsvkrvyivctedkgipeefqrwqidnigvteaieikgadhmamlcepqklcaslleia

HKYN*

